name = "deauboard"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "deauboard"
database_id = "285b9827-d8ea-4983-8ecf-39daefa3dbb2"
